name: DockerHub Image Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: main Branch Checkout
      uses: actions/checkout@v3
    
    - name: Download Generic Resources
      run: wget -O ./Resources/ffmpeg https://storage.googleapis.com/codeadeel-github/Generic/ffmpeg ; wget -O ./Resources/youtube-dl https://storage.googleapis.com/codeadeel-github/Generic/youtube-dl
    - name: Download Model Resources
      run: wget -O ./Resources/resnet18-f37072fd.pth https://storage.googleapis.com/codeadeel-github/Brand-Recognition/resnet18-f37072fd.pth ; wget -O ./Resources/Embeddings https://storage.googleapis.com/codeadeel-github/Brand-Recognition/Embeddings

    - name: Docker Login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
      
    - name: Build Server
      run: docker build -t ${{secrets.DOCKER_USER}}/brand_recognition:server -f Build_Server .
    - name: Push Server
      run: docker push ${{secrets.DOCKER_USER}}/brand_recognition:server
    
    - name: Build Embeddings Client
      run: docker build -t ${{secrets.DOCKER_USER}}/brand_recognition:embeddings -f Embeddings_Client .
    - name: Push Embeddings Client
      run: docker push ${{secrets.DOCKER_USER}}/brand_recognition:embeddings
    
    - name: Build Live Client
      run: docker build -t ${{secrets.DOCKER_USER}}/brand_recognition:live_client -f Live_Client .
    - name: Push Live Client
      run: docker push ${{secrets.DOCKER_USER}}/brand_recognition:live_client
    
    - name: Build Browser Based Live Client
      run: docker build -t ${{secrets.DOCKER_USER}}/brand_recognition:live_client_browser -f Live_Client_Browser .
    - name: Push Browser Based Live Client
      run: docker push ${{secrets.DOCKER_USER}}/brand_recognition:live_client_browser
    
    - name: Build RTSP Based Live Client
      run: docker build -t ${{secrets.DOCKER_USER}}/brand_recognition:live_client_rtsp -f Live_Client_RTSP .
    - name: Push RTSP Based Live Client
      run: docker push ${{secrets.DOCKER_USER}}/brand_recognition:live_client_rtsp
    
    - name: Build Browser Based Multi Live Client
      run: docker build -t ${{secrets.DOCKER_USER}}/brand_recognition:multi_live_browser -f Multi_Live_Client_Browser .
    - name: Push Browser Based Multi Live Client
      run: docker push ${{secrets.DOCKER_USER}}/brand_recognition:multi_live_browser
    
    - name: Build RTSP Based Multi Live Client
      run: docker build -t ${{secrets.DOCKER_USER}}/brand_recognition:multi_live_rtsp -f Multi_Live_Client_RTSP .
    - name: Push RTSP Based Multi Live Client
      run: docker push ${{secrets.DOCKER_USER}}/brand_recognition:multi_live_rtsp
    
    - name: Build Video Client
      run: docker build -t ${{secrets.DOCKER_USER}}/brand_recognition:video_client -f Video_Client .
    - name: Push Video Client
      run: docker push ${{secrets.DOCKER_USER}}/brand_recognition:video_client
    
    - name: Build Browser Based Video Client
      run: docker build -t ${{secrets.DOCKER_USER}}/brand_recognition:video_client_browser -f Video_Client_Browser .
    - name: Push Browser Based Video Client
      run: docker push ${{secrets.DOCKER_USER}}/brand_recognition:video_client_browser
    
    - name: Build RTSP Based Video Client
      run: docker build -t ${{secrets.DOCKER_USER}}/brand_recognition:video_client_rtsp -f Video_Client_RTSP .
    - name: Push RTSP Based Video Client
      run: docker push ${{secrets.DOCKER_USER}}/brand_recognition:video_client_rtsp
